version: 2.1

jobs:
  build_and_publish:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    worker_directory: ~/docker-helm
    steps:
      - checkout
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Build image
          command: |
            export HELM_VERSION=${CIRCLE_TAG:-v3.2.2}
            docker build --build-arg HELM_VERSION=${HELM_VERSION} -t verdigristech/helm:${HELM_VERSION} .
            ([ -n "${CIRCLE_TAG}" ] && docker tag verdigristech/helm:${HELM_VERSION} verdigristech/helm:latest) || true
      - run:
          name: Publish to Docker Hub
          command: |
            export HELM_VERSION=${CIRCLE_TAG:-v3.2.2}
            docker push verdigristech/helm:${HELM_VERSION}
            ([ -n "${CIRCLE_TAG}" ] && docker push verdigristech/helm:latest) || true

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build_and_publish:
          context: common
          filters:
            branches:
              only: /master/
            tags:
              only: /v\d+(\.\d+)*/
